# Basic Information
title: Yijie Li
position: Ph.D. Candidate
affiliation: University of Electronic Science and Technology of China
affiliation_link: http://www.uestc.edu.cn
email: yijie_li@std.uestc.edu.cn

domain: yishengpoxiao.github.io # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://yishengpoxiao.github.io # the base hostname and protocol for your site, e.g. http://example.com
plugins:
  - jekyll-sitemap
# baseurl: /REPOSITORY-NAME/      # place folder name if the site is served in a subfolder

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: Yijie Li, UESTC, Medical Image Analysis
description: Yijie Li is a Ph.D. candidate at UESTC specializing in diffusion MRI, tractography, and deep learning for neuroimaging.
canonical: https://yishengpoxiao.github.io/

# Analytics
google_analytics: G-X4TZ44T44J

# Links
# If you don't need one of them, you may delete the corresponding line.
social:
  - {
      platform: "GitHub",
      url: "https://github.com/yishengpoxiao",
      icon: "fab fa-github",
      font_size: "1.2rem",
    }
  - {
      platform: "Google Scholar",
      url: "https://scholar.google.com/citations?user=5beXu1kAAAAJ",
      icon: "ai ai-google-scholar",
      font_size: "1.3rem",
    }
  # - {
  #     platform: "LinkedIn",
  #     url: "https://www.linkedin.com/in/yourusername/",
  #     icon: "fab fa-linkedin",
  #     font_size: "1.2rem",
  #   }
  - {
      platform: "Email",
      url: "mailto:yijie_li@std.uestc.edu.cn",
      icon: "fas fa-envelope",
      font_size: "1.2rem",
    }
  - { 
      platform: 'CV',
      url: 'assets/files/yijie_li_cv.pdf',
      icon: 'ai ai-cv',
      font_size: '1.3rem'
    }
 
# Images (e.g., your profile picture and your website's favicon)
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively.
avatar: ./assets/img/favicon.ico # Replace with your profile picture
favicon: ./assets/img/uestc.png
favicon_dark: ./assets/img/uestc.png

# Footnote
# You may use the option to disable the footnote, "Powered by Jekyll and Minimal Light theme."
enable_footnote: true

# Auto Dark Mode
# You may use the option to disable the automatic dark theme
auto_dark_mode: true

# Font
# You can use this option to choose between Serif or Sans Serif fonts.
font: "Sans Serif" # or "Sans Serif"

# Google Analytics ID
# Please remove this if you don't use Google Analytics
# google_analytics: UA-111540567-4

# Use this project as a remote theme for GitHub Pages
# See the guide here: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll
remote_theme: KuangzhiGe/minimal-photon

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
